### ISSUE TITLE
shire: automated build script fails to build mordorwindowsserversstack 

### ISSUE THREAD

**Issue by punchdrunktux** [hunters-forge/Blacksmith#1]
./deploy-mordor.sh -e 'shire'

MordorWindowsServersStack fails with:

"FileServer"  ----- "Failed to receive 1 resource signal(s) within the specified duration"
"Resource creation cancelled"

And then initiates a rollback.  
-----
The following are successful:
MordorNetworkStack
MordorHELKStack
MordorC2Stack
MordorWindowsDCStack

Not sure how to troubleshoot this build error.

**Comment by Cyb3rWard0g** [comment]
One way to do it is to RDP to the box and check the logs in `c:\cfn\logs\` before it fails. Otherwise, it would be good to enable cloudtrail logs to the build. Something I am not familiar with yet.
- The Servers build should take 10-12 mins. In minute 10, I would RDP to the box with creds `Administrator:P1ls3n!`  and check the logs in the folder I shared above. Let me know if that works to get to the root of the problem.
